spring.application.name=colonyManagement
spring.datasource.url=jdbc:mysql://localhost:3306/colony_db
spring.datasource.username=root
spring.datasource.password=I@intstein0
spring.jpa.hibernate.ddl-auto=update
